# Generated by Django 4.2.1 on 2023-05-13 17:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('nomeGenerico', models.CharField(max_length=150)),
                ('imagem', models.CharField(max_length=150)),
                ('dosagens', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('formato', models.CharField(max_length=150)),
                ('administracao', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
            ],
        ),
    ]
