# Generated by Django 4.2.1 on 2023-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReceita', models.IntegerField()),
                ('userName', models.CharField(max_length=100)),
                ('userID', models.IntegerField()),
                ('medList', models.JSONField()),
            ],
        ),
    ]
