# Generated by Django 4.2.1 on 2023-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='medList',
            field=models.TextField(),
        ),
    ]
