# Generated by Django 4.2.1 on 2023-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('idReceita', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='historico',
            name='prescTotal',
            field=models.CharField(max_length=6),
        ),
    ]
